### ISSUE TITLE
Ubuntu 14.04 issue with Discordie

### ISSUE THREAD

**Issue by ibabbi** [qeled/discordie#13]
I'm getting the following error on my Ubuntu 14.04 machine, while the script works perfectly fine on Windows 10.

`client.Dispatcher.on("GATEWAY_READY", e => {
                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`

**Comment by abalabahaha** [comment]
Do you have NodeJS v4.0.0 or higher installed? If not, [NodeSource distributions](https://github.com/nodesource/distributions) or [Node Version Manager](https://github.com/creationix/nvm) are two ways to get Node 4+ on Ubuntu.

**Comment by ibabbi** [comment]
I had NodeJS 0.12. Installed 4.4.5 and it's working fine now. Thank you.
