### ISSUE TITLE
JSON parsing and WebSocket buffer copy errors with Node 6

### ISSUE THREAD

**Issue by mbilker** [qeled/discordie#15]
I am using the latest git version of Discordie, but in the past week or so my bot is crashing from the following errors:

```
undefined:1
{"t":"TYPING_START","s":535,"op":0,"d":{"user_id":"142098955818369024","timestamp":1468179526,"channel_id":"142072749911834625"}


SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at BaseSocket.ws.on.e (/home/mbilker/music-discord/node_modules/discordie/lib/networking/ws/GatewaySocket.js:128:24)
    at emitTwo (events.js:106:13)
    at BaseSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/mbilker/music-discord/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:364:5)
    at /home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:482:12)
```
and
```
/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/home/mbilker/music-discord/node_modules/ws/lib/Receiver.js:86:3)
    at TLSSocket.realHandler (/home/mbilker/music-discord/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```

The second error is more of an error with the WebSocket connection.

I have not investigated the cause of these yet or turned on debugging. I just wanted to report this.

**Comment by Ryu945** [comment]
I got this error as well.  Someone told me they got rid of this error by downgrading their version of nodejs.  I talked with people on #nodejs, from freenode.  They said that just because a downgrade fixes the problem, doesn't mean it is nodejs is bugged.



/var/lib/openshift/5787d8962d527145a0000115/app-root/runtime/repo/node_modules/discordie/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/var/lib/openshift/5787d8962d527145a0000115/app-root/runtime/repo/node_modules/discordie/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/var/lib/openshift/5787d8962d527145a0000115/app-root/runtime/repo/node_modules/discordie/node_modules/ws/lib/Receiver.js:86:3)
    at TLSSocket.realHandler (/var/lib/openshift/5787d8962d527145a0000115/app-root/runtime/repo/node_modules/discordie/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)

**Comment by RubbixCube** [comment]
From what I could tell, Node 6 seems to crash discordie.
I personally use Node 5.3.0, no issues here

**Comment by mbilker** [comment]
I am running Arch Linux.

I downloaded Node 4.4.7 LTS from the website and reinstalled all modules and this issue went away. It seems this an issue with Node 6.

**Comment by Ryu945** [comment]
The lastest update of Discordie fixed this for me.

**Comment by mbilker** [comment]
@songying This is an error in the `ws` library with `socket.io`, unrelated to Discordie. Are you using the latest version of Discordie and socket.io?

**Comment by songying** [comment]
@mbilker Yes , it's unrelated to Discordie. I just search my error and found this issue was disussing this.
