### ISSUE TITLE
IUser Crash

### ISSUE THREAD

**Issue by Ryu945** [qeled/discordie#20]
I believed the code I called to get this crash is ``e.message.author.getVoiceChannel(e.message.guild)`` .  I called this code inside of a direct message.  Here is the error message.

```/home/ryu/node_modules/discordie/lib/interfaces/IUser.js:212
      guild.valueOf(), this.id
           ^

TypeError: Cannot read property 'valueOf' of null
    at IUser.getVoiceChannel (/home/ryu/node_modules/discordie/lib/interfaces/IUser.js:212:12)
    at DiscordieDispatcher.<anonymous> (/home/ryu/.Discord_Bot/Lina_Inverse/Lina_Inverse.js:284:24)
    at emitOne (events.js:77:13)
    at DiscordieDispatcher.emit (events.js:169:7)
    at DiscordieDispatcher.emit (/home/ryu/node_modules/discordie/lib/core/DiscordieDispatcher.js:37:16)
    at Discordie.handler (/home/ryu/node_modules/discordie/lib/networking/messages/gateway/message_create.js:12:19)
    at Discordie.processMessage (/home/ryu/node_modules/discordie/lib/core/MessageHandlerCache.js:11:55)
```

This bug is being caused by the fact that inside a direct message, there is no guild id.  Discordie should have a way to handle this besides crashing.

edit: fixed the code that caused it

**Comment by acdenisSK** [comment]
you can still do 
```js
if (!e.message.channel.isPrivate) { 
   client.Guilds.get('a correction guild id string');
}
```
which should work fine

**Comment by qeled** [comment]
I believe you called `getVoiceChannel(guild)` and passed an invalid parameter (null) into the function. I could make it throw an error with a message, but that will still require handling on your side and results in the same code.

**Comment by Ryu945** [comment]
I see what actually caused this.  I called

``e.message.author.getVoiceChannel(e.message.guild)``
