### ISSUE TITLE
setAvatar throws

### ISSUE THREAD

**Issue by CKing** [qeled/discordie#36]
Running `setAvatar` on my bot throws an error with http code 401
```
> d.User.setAvatar("path/to.image").then(console.log, console.log)
Promise { <pending> }

> { Error: Unauthorized
    at Request.callback (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  original: null,
  response: 
   Response {
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 401,
        statusMessage: 'UNAUTHORIZED',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"code": 0, "message": "401: Unauthorized"}',
        read: [Function],
        body: [Object] },
     request: 
      Request {
        domain: [Object],
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'PATCH',
        url: 'https://discordapp.com/api/users/@me',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _data: [Object],
        req: [Object],
        protocol: 'https:',
        host: 'discordapp.com',
        _callback: [Function],
        res: [Object],
        response: [Circular],
        _timeout: 0,
        called: true },
     req: 
      ClientRequest {
        domain: [Object],
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 113,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'PATCH /api/users/@me HTTP/1.1\r\nHost: discordapp.com\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: DiscordBot (https://github.com/qeled/discordie, v0.7.6) (Linux 4.4.0-34-generic; x64) node/6.3.1 openssl/1.0.2h\r\nContent-Type: application/json\r\nContent-Length: 113\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'PATCH',
        path: '/api/users/@me',
        _ended: true,
        parser: null,
        res: [Object] },
     links: {},
     text: '{"code": 0, "message": "401: Unauthorized"}',
     body: { code: 0, message: '401: Unauthorized' },
     files: {},
     buffered: true,
     headers: 
      { date: 'Fri, 12 Aug 2016 19:32:11 GMT',
        'content-type': 'application/json',
        'content-length': '43',
        connection: 'close',
        'set-cookie': [Object],
        'strict-transport-security': 'max-age=31536000; includeSubdomains',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '2d165a13c9e42d41-TXL' },
     header: 
      { date: 'Fri, 12 Aug 2016 19:32:11 GMT',
        'content-type': 'application/json',
        'content-length': '43',
        connection: 'close',
        'set-cookie': [Object],
        'strict-transport-security': 'max-age=31536000; includeSubdomains',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '2d165a13c9e42d41-TXL' },
     statusCode: 401,
     status: 401,
     statusType: 4,
     info: false,
     ok: false,
     redirect: false,
     clientError: true,
     serverError: false,
     error: 
      { Error: cannot PATCH /api/users/@me (401)
          at Response.toError (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/response.js:106:13)
          at Response.setStatusProperties (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/response.js:42:8)
          at IncomingMessage.<anonymous> (/home/criss/Projects/symphonia/node_modules/discordie/node_modules/superagent/lib/node/index.js:918:22)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:975:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickDomainCallback (internal/process/next_tick.js:122:9)
        status: 401,
        text: '{"code": 0, "message": "401: Unauthorized"}',
        method: 'PATCH',
        path: '/api/users/@me' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: true,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 401 }
```

**Comment by CKing** [comment]
never mind, it works now. not sure what happened
