### ISSUE TITLE
Node.js update breaks Discordie

### ISSUE THREAD

**Issue by Ryu945** [qeled/discordie#74]
Here is what I have of an error log.  This occured after the only code change was an update to node.js.

```
at IAuthenticatedUser.can (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/interfaces/IUser.js:231:26)
    at IAuthenticatedUser.can (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/interfaces/IAuthenticatedUser.js:289:32)
    at DiscordieDispatcher.client.Dispatcher.on.e (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/start.js:344:20)
    at emitOne (events.js:96:13)
    at DiscordieDispatcher.emit (events.js:189:7)
    at DiscordieDispatcher.emit (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/core/DiscordieDispatcher.js:37:16)
    at Discordie.handler (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/networking/messages/gateway/message_create.js:12:19)
    at Discordie.processMessage (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/core/MessageHandlerCache.js:11:55)
    at MessageHandlerCache.processGatewayMessage (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/core/MessageHandlerCache.js:53:27)
    at DiscordieDispatcher.Dispatcher.on.e (/var/lib/openshift/58990b4d0c1e66658a00015c/app-root/runtime/repo/node_modules/discordie/lib/index.js:82:19)
```

**Comment by potaha** [comment]
Have you tried to install Node.JS 6?

**Comment by Ryu945** [comment]
After doing some restarts, the bot is not crashing so perhaps this is some other bug that happened to be triggered during an update.
