### ISSUE TITLE
Issue with mention

### ISSUE THREAD

**Issue by Lukkez** [qeled/discordie#8]
I just got a error when i was making a mentionme command, see that
ReferenceError: user is not defined
    at DiscordieDispatcher.<anonymous> (/home/ubuntu/workspace/bot.js:40:39)
    at emitOne (events.js:82:20)
    at DiscordieDispatcher.emit (events.js:169:7)
    at Discordie.handler (/home/ubuntu/workspace/node_modules/discordie/lib/networking/messages/gateway/message_create.js:12:19)
    at Discordie.processMessage (/home/ubuntu/workspace/node_modules/discordie/lib/core/MessageHandlerCache.js:11:55)
    at MessageHandlerCache.processGatewayMessage (/home/ubuntu/workspace/node_modules/discordie/lib/core/MessageHandlerCache.js:44:27)
    at DiscordieDispatcher.<anonymous> (/home/ubuntu/workspace/node_modules/discordie/lib/index.js:78:19)
    at emitOne (events.js:82:20)
    at DiscordieDispatcher.emit (events.js:169:7)

client.Dispatcher.on(Events.MESSAGE_CREATE, e => {
    if(e.message.content == '[mentionme]') {
        e.message.channel.sendMessage(user.nickMention + ", example mention");
    }
});
that's all my code

**Comment by TheEvilSocks** [comment]
user is not an existing variable.

**Comment by Lukkez** [comment]
On the docs user is a existing variable, what should i use?

**Comment by qeled** [comment]
Get the user you want to mention from the message:
```js
client.Dispatcher.on("MESSAGE_CREATE", e => {
  if (e.message.content == '[mentionme]') {
    var user = e.message.author;
    e.message.channel.sendMessage(user.nickMention + ", example mention");
  }
});
```

**Comment by Lukkez** [comment]
Oh, thanks i don't remembered that =p stupid error
